apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source.yaml
  - sync.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: ww-gitops-values
    namespace: flux-system
    files:
      - values.yaml=values.enc.yaml
configurations:
  - kustomizeconfig.yaml
