apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description: This is the Weave GitOps Dashboard.  It provides
      a simple way to get insights into your GitOps workloads.
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  serviceAccountName: kustomize-controller
  interval: 0h1m0s
  values:
    WEAVE_GITOPS_FEATURE_TELEMETRY: "true"
    adminUser:
      create: true
      passwordHash: $2b$12$Hc0FZCMy8KLRajb8LWYFqOvsMZcvLzlSOumSLwK4xud1r3QheQqlu
      username: admin
